version: '3'

services:
    mariadb:
        container_name: mariadb
        image: mariadb:latest
        ports:
            - 3306:3306
        volumes:
            - mariadb-data:/var/lib/mysql
        env_file:
            - .env
        networks:
            - mariadb

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        env_file:
            - .env
        networks:
            - mariadb
        links:
            - mariadb:mariadb

volumes:
    mariadb-data:
        driver: local

networks:
    mariadb:
        driver: bridge
