version: '3'

services:
    postgres:
        container_name: postgres
        image: postgres:latest
        ports:
            - 5432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
        env_file:
            - .env
        networks:
            - postgres

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        ports:
            - 8080:80
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        env_file:
            - .env
        networks:
            - postgres
        links:
            - postgres:postgres

volumes:
    postgres-data:
        driver: local
    pgadmin-data:
        driver: local

networks:
    postgres:
        driver: bridge
